# Generated by Django 4.2.18 on 2025-02-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_absence', models.IntegerField(verbose_name='nombre_absence')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('specialite', models.CharField(max_length=50, verbose_name='specialite')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=50, verbose_name='motif')),
                ('dateAbsence', models.CharField(max_length=50, verbose_name='dateAbsence')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GesPerson.eleve')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
    ]
